"""initial migration

Revision ID: c468f97c3a03
Revises: 
Create Date: 2026-03-25 04:31:01.162820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c468f97c3a03'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('idea', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'IN_REVIEW', 'APPROVED', 'REJECTED', name='productstatus'), nullable=True),
    sa.Column('strategist_output', sa.JSON(), nullable=True),
    sa.Column('market_research_output', sa.JSON(), nullable=True),
    sa.Column('prd_output', sa.JSON(), nullable=True),
    sa.Column('tech_architecture', sa.JSON(), nullable=True),
    sa.Column('ux_design', sa.JSON(), nullable=True),
    sa.Column('qa_strategy', sa.JSON(), nullable=True),
    sa.Column('final_prd', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('state', sa.JSON(), nullable=True),
    sa.Column('current_node', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    op.drop_table('products')
    # ### end Alembic commands ###
